<?php
// AWRMS configuration - generated by package postinst
return [
    'db' => [
        'host' => 'localhost',
        'name' => 'awrms',
        'user' => 'awrms_user',
        'pass' => 'awrms_pass',
    ],
    'media_dir' => '/var/www/html/awrms/media',
    'icecast' => [
        'mount' => '/stream',
        'host' => 'localhost',
        'port' => 8000
    ]
];
